services:
  service-template:
    build: .
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/template
    ports: [ "8080:8080" ]
    depends_on: [ postgres ]

  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=template
      - POSTGRES_PASSWORD=template
      - POSTGRES_DB=template
    ports: [ "5432:5432" ]
