services:
  service-template:
    build: .
    environment:
      SERVER_PORT: 8080
    ports: [ "8080:8080" ]

  postgres-db:
    image: postgres:11.5-alpine
    container_name: service-template-postgres
    environment:
      - POSTGRES_USER=service-template
      - POSTGRES_PASSWORD=service-template
      - POSTGRES_DB=service-template
    ports:
      - "5432:5432"
