---
server:
  port: "${PORT:8080}"
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/template}"
    username: "${SPRING_DATASOURCE_USERNAME:template}"
    password: "${SPRING_DATASOURCE_PASSWORD:template}"
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: non_absent
    locale: en_US
    time-zone: UTC
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  kafka:
    bootstrap-servers: "${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
    consumer:
      group-id: com.johncnstn
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: com.johncnstn.servicetemplate.event.model # change this with your event packages
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      concurrency: 3
      ack-mode: manual

springdoc:
  swagger-ui:
    use-root-path: true
