---
server:
  port: 8080
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/template
    username: template
    password: template
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: non_absent
    locale: en_US
    time-zone: UTC
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
